apiVersion: v1
kind: Service
metadata:
  name: login-app
  namespace: login-app
spec: 
  type: NodePort 
  selector:
    app: login-app
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080


